namespace Rawr.RestoSham
{
    public static class RelevantStats
    {
        public static string[] StatList = { 
            "Stamina",
            "Intellect",
            "SpellPower",
            "CritRating",
            "HasteRating",
            "SpellCrit",
            "SpellHaste",
            "Mana",
            "Mp5",
            "Earthliving",
            "ManacostReduceWithin15OnHealingCast",
            "ManaRestoreFromMaxManaPerSecond",
            "BonusManaPotion",
            "WaterShieldIncrease",
            "CHHWHealIncrease",
            "CHCTDecrease",
            "RTCDDecrease",
            "TotemCHBaseHeal",
            "TotemHWBaseCost",
            "TotemCHBaseCost",
            "TotemHWSpellpower",
            "TotemLHWSpellpower",
            "TotemThunderhead",
            "ManaRestore",
            "BonusCritHealMultiplier",
            "BonusManaMultiplier",
            "BonusIntellectMultiplier",
            "RestoSham2T9",
            "RestoSham4T9",
            "RestoSham2T10",
            "RestoSham4T10",
            "RestoShamRelicT9",
            "RestoShamRelicT10",
            "FireDamage",
            "Healed",
            "Hp5"
        };
    }
}
