#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.208
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rawr.Server
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Rawr")]
	public partial class RawrDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public RawrDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["RawrConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public RawrDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RawrDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RawrDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RawrDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CharacterHTML> CharacterHTMLs
		{
			get
			{
				return this.GetTable<CharacterHTML>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="rawrserver.CharacterHTML")]
	public partial class CharacterHTML
	{
		
		private string _CharacterName;
		
		private string _Realm;
		
		private string _Region;
		
		private System.DateTime _LastRefreshed;
		
		private string _HTML;
		
		public CharacterHTML()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CharacterName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CharacterName
		{
			get
			{
				return this._CharacterName;
			}
			set
			{
				if ((this._CharacterName != value))
				{
					this._CharacterName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Realm", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Realm
		{
			get
			{
				return this._Realm;
			}
			set
			{
				if ((this._Realm != value))
				{
					this._Realm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Region", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string Region
		{
			get
			{
				return this._Region;
			}
			set
			{
				if ((this._Region != value))
				{
					this._Region = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastRefreshed", DbType="DateTime NOT NULL")]
		public System.DateTime LastRefreshed
		{
			get
			{
				return this._LastRefreshed;
			}
			set
			{
				if ((this._LastRefreshed != value))
				{
					this._LastRefreshed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HTML", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string HTML
		{
			get
			{
				return this._HTML;
			}
			set
			{
				if ((this._HTML != value))
				{
					this._HTML = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
