//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rawr.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class CacheSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static CacheSettings defaultInstance = ((CacheSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CacheSettings())));
        
        public static CacheSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("images")]
        public string RelativeItemImageCache {
            get {
                return ((string)(this["RelativeItemImageCache"]));
            }
            set {
                this["RelativeItemImageCache"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("talent_images")]
        public string RelativeTalentImageCache {
            get {
                return ((string)(this["RelativeTalentImageCache"]));
            }
            set {
                this["RelativeTalentImageCache"] = value;
            }
        }
    }
}
